Week2
joomla-projects/gsoc21_media-manager pull request #8
Opened 2021-06-19 17:21 UTC by eyvazahmadzada

Pull Request for issues #6 and #7.

### Summary of Changes
- Implemented **automatic deletion** of responsive images when they are no longer needed: when they get removed from the content or media manager.
- Added responsive image generation to **every content editor and form** where it's needed by using helper functions.

### Testing Instructions
Go to the categories, banners, contacts, articles, or newsfeeds pages and add an image to the content editor or form. Then check out the responsive directory created in the folder where the original image is stored, responsive versions will be there. Now delete the original image, responsive versions will be gone.

2021-06-22 13:42 UTC, sebenns requested changes

2021-06-22 13:42 UTC, sebenns commented on libraries/src/Helper/MediaHelper.php
> +		$pattern = '/src="([^"]+)"/';
What happens if someone provides $initContent that sort of content, that contains other tags with a src attribute? F.e. audio, video, embed, input, iframe (...).  

have a look @$data['articletext']

2021-06-22 19:14 UTC, sebenns approved these changes
lgtm

2021-06-23 12:34 UTC, sebenns requested changes
https://ci.joomla.org/joomla-projects/gsoc21_media-manager/7/1/6 - Check that out.

2021-06-23 16:56 UTC, eyvazahmadzada commented
I pushed a new commit for fixing the violations, but the build log says that "Build is blocked, please, contact repo admin in order to proceed".

2021-06-23 17:47 UTC, sebenns commented
Benjamin has approved the pipe, you can at least check that: https://ci.joomla.org/joomla-projects/gsoc21_media-manager/10.

Don't forget to pull from dev, should work then.

2021-06-23 20:15 UTC, fancyFranci approved these changes

2021-06-23 20:15 UTC, fancyFranci commented on administrator/components/com_categories/src/Model/CategoryModel.php
> +			// Initial version
In my opinion such comments are unnecessary, because you already have good names for the variables ($initImage/$finalImage) :)

2021-06-23 20:15 UTC, fancyFranci commented on libraries/src/Helper/MediaHelper.php
> +	protected static $responsiveSizes = array('800x600', '600x400', '400x200');
Just to be sure: You plan to make the sizes configurable, right?

2021-06-23 20:15 UTC, fancyFranci commented on libraries/src/Image/Image.php
> +				if (preg_replace('/_[^_][0-9]+x[0-9]+[^.]*/', '', $imageFile) === end($image))
Regex patterns are hard to read. Please provide a matching example in the comment above :)

2021-06-23 20:15 UTC, fancyFranci commented on administrator/components/com_contact/src/Model/ContactModel.php
> +			MediaHelper::generateResponsiveFormImages($initImage, $finalImage);
It's sad, that you need to write so much (nearly) duplicated code. But I don't have a solution yet :/

2021-06-24 05:48 UTC, eyvazahmadzada commented
Thank you for your comments @fancyFranci, I will work on them and try to remove duplicate code as much as possible. 
By the way, the static variable $responsiveSizes is going to be changed when I add the custom image generation feature, so it's not here to stay :)

2021-06-25 11:43 UTC, sebenns approved these changes

2021-07-06 14:05 UTC, merged